In [1]:
!pip install numpy
import numpy as np

### exercise 1

In [9]:
answer1 = np.arange(1,17)
answer1.reshape(4,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

### exercise 2

In [21]:
answer2 = np.arange(10,51,5)
answer2.resize (2,4)
display(answer2)

array([[10, 15, 20, 25],
       [30, 35, 40, 45]])

### exercise 3

In [41]:
np.random.seed(1)
answer3 = np.random.randint (1,101,(3,3))
print(answer3)
print('max:', answer3.max())
print('min:', answer3.min())

[[38 13 73]
 [10 76  6]
 [80 65 17]]
max: 80
min: 6


### exercise 4

In [67]:
answer4 = np.arange(0,20,2)
display(answer4)
display(answer4[:5])
display(answer4[::2])
display(answer4[::-1])

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

array([0, 2, 4, 6, 8])

array([ 0,  4,  8, 12, 16])

array([18, 16, 14, 12, 10,  8,  6,  4,  2,  0])

### exercise 5

In [79]:
np.random.seed(1)
answer5 = np.random.randint(0,51,(4,5))
display(answer5)
display(answer5[1,3])

array([[37, 43, 12,  8,  9],
       [11,  5, 15,  0, 16],
       [ 1, 12,  7, 45,  6],
       [25, 50, 20, 37, 18]])

0

### exercise 6

In [91]:
np.random.seed(1)
answer6 = np.random.randint(0,101,15)
display(answer6)
display(answer6.argmax())
display(answer6.argmin())

array([37, 12, 72,  9, 75,  5, 79, 64, 16,  1, 76, 71,  6, 25, 50])

6

9